// megafunction wizard: %PARALLEL_ADD%VBB%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: parallel_add 

// ============================================================
// File Name: G_get.v
// Megafunction Name(s):
// 			parallel_add
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 16.1.0 Build 196 10/24/2016 SJ Lite Edition
// ************************************************************

//Copyright (C) 2016  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Intel and sold by Intel or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.

module G_get (
	clock,
	data0x,
	data1x,
	data2x,
	data3x,
	data4x,
	data5x,
	result);

	input	  clock;
	input	[10:0]  data0x;
	input	[10:0]  data1x;
	input	[10:0]  data2x;
	input	[10:0]  data3x;
	input	[10:0]  data4x;
	input	[10:0]  data5x;
	output	[13:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "MAX 10"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: MSW_SUBTRACT STRING "NO"
// Retrieval info: CONSTANT: PIPELINE NUMERIC "1"
// Retrieval info: CONSTANT: REPRESENTATION STRING "SIGNED"
// Retrieval info: CONSTANT: RESULT_ALIGNMENT STRING "LSB"
// Retrieval info: CONSTANT: SHIFT NUMERIC "0"
// Retrieval info: CONSTANT: SIZE NUMERIC "6"
// Retrieval info: CONSTANT: WIDTH NUMERIC "11"
// Retrieval info: CONSTANT: WIDTHR NUMERIC "14"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT GND "clock"
// Retrieval info: USED_PORT: data0x 0 0 11 0 INPUT NODEFVAL "data0x[10..0]"
// Retrieval info: USED_PORT: data1x 0 0 11 0 INPUT NODEFVAL "data1x[10..0]"
// Retrieval info: USED_PORT: data2x 0 0 11 0 INPUT NODEFVAL "data2x[10..0]"
// Retrieval info: USED_PORT: data3x 0 0 11 0 INPUT NODEFVAL "data3x[10..0]"
// Retrieval info: USED_PORT: data4x 0 0 11 0 INPUT NODEFVAL "data4x[10..0]"
// Retrieval info: USED_PORT: data5x 0 0 11 0 INPUT NODEFVAL "data5x[10..0]"
// Retrieval info: USED_PORT: result 0 0 14 0 OUTPUT NODEFVAL "result[13..0]"
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @data 0 0 11 0 data0x 0 0 11 0
// Retrieval info: CONNECT: @data 0 0 11 11 data1x 0 0 11 0
// Retrieval info: CONNECT: @data 0 0 11 22 data2x 0 0 11 0
// Retrieval info: CONNECT: @data 0 0 11 33 data3x 0 0 11 0
// Retrieval info: CONNECT: @data 0 0 11 44 data4x 0 0 11 0
// Retrieval info: CONNECT: @data 0 0 11 55 data5x 0 0 11 0
// Retrieval info: CONNECT: result 0 0 14 0 @result 0 0 14 0
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL G_get_bb.v TRUE
// Retrieval info: LIB_FILE: altera_mf
